name: mercado_cercano_workspace
publish_to: 'none'

environment:
  sdk: ^3.11.5

dev_dependencies:
  melos: ^7.0.0

workspace:
  - packages/mc_domain
  - packages/mc_application
  - packages/mc_infrastructure
  - packages/mc_design_system
  - packages/mc_hardware
  - apps/mc_pos
  - apps/mc_consumer
  - apps/mc_admin
